apps/schools/urls.py
from django.conf.urls import url

from .views import SchoolList, SchoolDetail, SchoolComment, already_studied_here

urlpatterns = [
    url(r'^$', SchoolList.as_view(), name='school-list'),
    url(r'profile/(?P<pk>\d+)/$', SchoolDetail.as_view(), name='school-profile'),
    url(r'profile/(?P<pk>\d+)/alreadystdhere/$', already_studied_here,
        name='school-profile-alreadystdhere'),
    url(r'profile/(?P<pk>\d+)/comment/$', SchoolComment.as_view(),
        name='school-profile-comment')

]

school_stalker/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken import views
from .social_auth import FacebookLogin
from .social_auth import GoogleLogin
from .social_auth import TwitterLogin


urlpatterns = [
    url(r'^', include('apps.core.urls', namespace=u"core")),
    url(r'^schools/', include('apps.schools.urls', namespace=u"schools")),
    url(r'^address/', include('apps.adresses.api.urls', namespace=u"adresses")),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/api-token-auth/', views.obtain_auth_token),
    url(r'^reports/', include('apps.reports.urls')),

    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^rest-auth/registration/', include('rest_auth.registration.urls')),
    url(r'^rest-auth/facebook/$', FacebookLogin.as_view(), name='fb_login'),
    url(r'^rest-auth/google/$', GoogleLogin.as_view(), name='google_login'),
    url(r'^rest-auth/twitter/$', TwitterLogin.as_view(), name='twitter_login')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/schools/models.py
from django.utils.translation import ugettext_lazy as _
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from ..utils.rating_categories import RATINGS_CATEGORIES
from ..profile.models import Profile
from django.db.models import Avg
from ckeditor.fields import RichTextField
from django.utils.text import slugify

from apps.adresses.models import City

NO_IMAGE = 'http://school-stalker.herokuapp.com/static/assets/img/circle2.png'


class Accommodation(models.Model):

    TYPE_OF_ACOMMODATIONS = (
        ("school_house", "Student Acommodation"),
        ("home_stay", "Home Stay"),
        ("hostel", "Hostel")
    )

    is_beakfest_included = models.BooleanField(
        _(u"Is BreakFeast included?"),
        help_text=_(u"Is BreakFest Included?"),
        default=False
    )

    is_lunch_included = models.BooleanField(
        _(u"Is Lunch included?"),
        help_text=_(u"Is lunch Included?"),
        default=False
    )

    is_dinner_included = models.BooleanField(
        _(u"Is Dinner Included?"),
        help_text=_(u"Is dinner Included?"),
        default=False
    )

    is_tv_in_the_bedroom = models.BooleanField(
        _(u"Do you have a tv in the bedroom?"),
        help_text=_(u"Do you have a tv in the bedroom?"),
        default=False
    )

    is_wardrobe_in_the_bedroom = models.BooleanField(
        _("Do you have a wardrobe in the bedroom?"),
        help_text=_(u"Do you have a wardrobe in the bedroom?"),
        default=False
    )

    is_air_in_the_badroom = models.BooleanField(
        _("Do you have a air conditioning in the bedroom?"),
        help_text=_(u"Do you have a air conditioning in the bedroom?"),
        default=False
    )

    duration = models.CharField(
        _(u"Period of stay in"),
        help_text=_(u"Time of acomodation"),
        max_length=255
    )

    wifi_free = models.BooleanField(
        _(u"Do you have free wifi?"),
        help_text=_(u"Do you have free wifi?"),
        default=False
    )

    time_to_school = models.CharField(
        _(u"How much time it take from the school?"),
        max_length=255,
        help_text=_(u"How much time it take from the school?")
    )

    differentials = models.CharField(
        _(u"Tell Me about your differentials"),
        help_text=_(u"What is your accomodation's differential"),
        max_length=255
    )

    def __str__(self):
        return str(self.id)


class Languages(models.Model):
    description = models.CharField(max_length=20)
    initials = models.CharField(max_length=5)

    def __str__(self):
        return self.description + ' - ' + self.initials


class SchoolCertificate(models.Model):
    name = models.CharField(max_length=150, null=False, blank=False)
    description = models.CharField(max_length=200, null=True, blank=True)
    image = models.ImageField(upload_to='certificate')
    url = models.CharField(max_length=300, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_image(self):
        return self.image.url if self.image else NO_IMAGE


class Facilities(models.Model):
    name = models.CharField(null=False, blank=False, max_length=100)
    icon_text = models.CharField(null=True, blank=True, max_length=30,
                                 help_text='Informe o nome do icone (https://materializecss.com/icons.html)')
    image = models.ImageField(null=True, blank=True, upload_to='facilities',
                              help_text='Caso não tenha um ícone no site, '
                                        'envie aqui a imagem. Lembre-se que'
                                        ' a imgem deve ser pequena, ter '
                                        'qualidade e seguir o padrão de design')

    def __str__(self):
        return self.name


class School(models.Model):
    """
        School model class.
        Set school information in database models
    """
    # short_phrase = models.TextField(null=True, blank=True)
    short_phrase = RichTextField(null=True, blank=True)

    name = models.CharField(
        _(u'School Name'),
        max_length=255,
        db_index=True
    )

    logo_image = models.ImageField(
        _(u"Upload o logo do seu computador"),
        upload_to='schools',
        blank=True
    )
    address = models.CharField(max_length=200,
        help_text=_(u"Informe o endereço da escola"),
        null=True, blank=True
    )
    neighborhood = models.CharField(max_length=200,
        help_text=_(u"Informe o bairro"),
        null=True, blank=True
    )

    city = models.ForeignKey(
        City, null=True, blank=True, verbose_name='Informe a cidade')

    youtube_channel_link = models.CharField(
        _(u"Youtube Channel"),
        help_text=_(u"Set the link for yout youtube channel or video"),
        max_length=255, null=True, blank=True
    )

    facebook_page = models.CharField(
        _(u"Facebook Page"),
        help_text=_(u"Facebook Page"),
        max_length=255, null=True, blank=True
    )

    twitter_page = models.CharField(
        _(u"Twitter Page"),
        help_text=_(u"Twitter Page"),
        max_length=500, null=True, blank=True
    )

    website = models.CharField(
        _(u"WebSite"),
        help_text=_(u"Your website"),
        max_length=255, null=True, blank=True
    )

    instagram = models.CharField(
        _(u"Instagram"),
        max_length=255,
        help_text=_(u"Instagram profile"), null=True, blank=True
    )

    admin_email = models.EmailField(
        _(u'Email'),
        max_length=100,
        unique=True,
        help_text=_(u"Email de contato da escola"), null=True, blank=True
    )

    phone = models.CharField(
        _(u'telefone'),
        max_length=18,
        null=True, blank=True,
        help_text=_(u"Ex.: +55 11 91001 0101")
    )

    internationa_phone = models.CharField(
        _(u'telefone'),
        max_length=18,
        null=True, blank=True,
        help_text=_(u"Ex.: +55 11 91001 0101")
    )

    registration_fee = models.DecimalField(
        _(u"Registration Fee Price"),
        max_digits=10,
        help_text=_(u"Registration Fee Price"),
        decimal_places=2,
        null=True,
        blank=True,
        default=0
    )

    workbook = models.DecimalField(
        _(u"Workbook Price"),
        max_digits=10,
        help_text=_(u"HWorkbook Price"),
        decimal_places=2,
        null=True,
        blank=True,
        default=0
    )

    refounds = models.DecimalField(
        _(u"Redounds"),
        max_digits=10,
        help_text=_(u"Refounds"),
        decimal_places=2,
        null=True,
        blank=True,
        default=0
    )

    low_season = models.CharField(
        _(u"Low season"),
        max_length=400,
        help_text=_(u"Low season"),
        null=True,
        blank=True
    )

    high_season = models.CharField(
        _(u"High season"),
        max_length=400,
        help_text=_(u"High season"),
        null=True,
        blank=True
    )

    work_time = models.TextField(
        verbose_name=_('Working time'),
        help_text=_('Inform the working time'), blank=True, null=True
    )

    coords = models.CharField(
        max_length=100, null=True, blank=True, verbose_name='Coordenadas')

    embeded_map = models.TextField(null=True, blank=True)

    accomodation = models.ForeignKey(
        Accommodation, null=True, blank=True)

    language = models.ForeignKey(Languages, null=True, blank=True)

    google_api_code = models.CharField(
        max_length=200, verbose_name='Código do Google Api', null=True,
        blank=True, unique=True)

    highlighted = models.BooleanField(verbose_name=_('Em destaque'),
                                      default=False,
                                      help_text='Se a escola estará em destaque no site.')
    slug = models.SlugField(max_length=255, unique=True, null=True, blank=False)

    show_budget = models.BooleanField(verbose_name=_('Apresentar orçamento no site'),
                                      default=False,
                                      help_text='Após cadastrar os cursos, '
                                                'periodos e valores da escola, '
                                                'marque essa opção para '
                                                'apresentar o botão de '
                                                'orçamento na listagem de '
                                                'escolas do site')

    certificates = models.ManyToManyField(SchoolCertificate, blank=True)
    facilities = models.ManyToManyField(Facilities, blank=True)
    favorite_users = models.ManyToManyField(Profile, related_name='favorite_schools', blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(School, self).save(*args, **kwargs)

    @property
    def events(self):
        return self.eventsoffered_set.get_queryset()

    @property
    def ratings(self):
        rating_total = self.rating_set.get_queryset().aggregate(
            Avg('stars')).get('stars__avg')
        rating_total = round(rating_total, 2) if rating_total else 1
        return rating_total

    @property
    def gallery(self):
        return self.gallery

    @property
    def videos(self):
        return self.videos_set.get_queryset()

    @property
    def ratings_count(self):
        return self.ratings_set.get_queryset().count()

    @property
    def comments(self):
        return self.comment_set.all()

    @property
    def full_rating(self):
        ratings = Rating.objects.filter(school=self.pk)
        res = {}

        for rating in ratings:
            if rating.type_of_rating not in res:
                res[rating.type_of_rating] = {}
                res[rating.type_of_rating]['sum'] = 0
                res[rating.type_of_rating]['qtd'] = 0
                res[rating.type_of_rating]['total'] = 0

apps/schools/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment', 'school', 'user')
#     name = forms.CharField(max_length=100)
#     email = forms.EmailField()
#     comment = forms.Textarea()

apps/schools/views.py
from django.views.generic import ListView, DetailView, FormView
from django.conf import settings
from django.shortcuts import resolve_url, redirect, HttpResponseRedirect

from .models import School, Comment, AlreadyStudiedHere
from .forms import CommentForm


class SchoolList(ListView):
    model = School
    template_name = 'schools/school_list.html'

    def get_queryset(self):
        queryset = School.objects.all()

        if self.request.GET.get('country'):
            country = self.request.GET.get('country')
            queryset = School.objects.filter(
                address__neighborhood__city__state__country__name__icontains=country)

        return queryset

    def get_context_data(self, **kwargs):
        context = super(SchoolList, self).get_context_data(**kwargs)
        context['country'] = self.request.GET.get('country', '')
        return context


class SchoolDetail(DetailView):
    model = School

    def get_context_data(self, **kwargs):
        context = super(SchoolDetail, self).get_context_data(**kwargs)
        context['categories'] = settings.RATINGS_CATEGORIES

        if self.request.user.is_authenticated:
            form = CommentForm(
                instance=Comment(
                    school=self.object, user=self.request.user.profile
                )
            )
            context['form'] = form

            ash = AlreadyStudiedHere.objects.filter(
                school=self.object, user=self.request.user.profile)
            context['already_studied_here'] = ash
        context['comments'] = Comment.objects.filter(
            school=self.get_object(), approved=True)
        return context


class SchoolComment(FormView):
    form_class = CommentForm

    def get_success_url(self):
        return resolve_url('schools:school-profile', self.kwargs.get('pk'))

    def form_valid(self, form):
        form.save()
        return super(SchoolComment, self).form_valid(form)


def already_studied_here(request, pk):
    if request.user.is_authenticated:
        school = School.objects.get(pk=pk)
        ash = AlreadyStudiedHere.objects.filter(school=school,
                                                user=request.user.profile)
        if ash:
            ash.delete()
        else:
            AlreadyStudiedHere.objects.create(
                school=school, user=request.user.profile)

        return redirect('schools:school-profile', pk)
    else:
        return HttpResponseRedirect('/accounts/login/?next=/schools/profile/1/')

apps/schools/templates/schools_combo/detail_school.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block header_title %}
<span class="mdl-layout-title">{{ page }}</span>
{% endblock %}
{% block body %}

<div class="container">
  <div class="row">
  <table class="highlight">
    <thead>
      <tr>
          <th data-field="id">Country Id</th>
          <th data-field="id">Country Name</th>
          <th data-field="name">Country Shrot Name</th>
          <th data-field="price">Currency</th>
      </tr>
    </thead>

    <tbody>
        <tr >
          <td>{{ object.pk }}</td>
          <td>{{ object.country_name }}</td>
          <td>{{ object.short_name }}</td>
          <td>{{ object.currency }}</td>
        </tr>
    </tbody>
    </table>
   </div>
 </div>


{% endblock %}

apps/schools/templates/schools_combo/edit_school_form.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block header_title %}
<span class="mdl-layout-title">{{ page }}</span>
{% endblock %}
{% block body %}

<div class="container">
 	<div class="row">
	    <form id="new_school_form" class="col s12" id="chart_type_form_first_step" method="post" enctype="multipart/form-data" action="{% url 'schools:edit_schools_country' object.pk %}">
	      <div class="row">
	        {% csrf_token %}
	        <div class="input-field col s12">
	          {{ form.country_name }}
	          <label class="active" for="id_text_subtitle">{{ form.country_name.help_text }}</label>
	        </div>
	        <div class="input-field col s12">
	          {{ form.short_name }}
	          <label class="active" for="id_datasource">{{ form.short_name.help_text }}</label>
	        </div>
	        <div class="input-field col s12">
	          {{ form.currency }}
	          <label class="active" for="id_datasource">{{ form.currency.help_text }}</label>
	        </div>
	    </form>
	    <a id="submit" name="send" class="waves-effect waves-light btn right">Salvar</a>
	  </div>
  </div>
</div>
<script type="text/javascript">
	$("#submit").click(function(){
		$("#new_school_form").submit();
	})

</script>
{% endblock %}

apps/schools/templates/schools_combo/list_schools.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block header_title %}
<span class="mdl-layout-title">{{ page }}</span>
{% endblock %}
{% block body %}

<div class="container">
  <div class="row">
  <table class="highlight">
    <thead>
      <tr>
          <th data-field="id">Country Id</th>
          <th data-field="id">Country Name</th>
          <th data-field="name">Short Name</th>
          <th data-field="price">Currency</th>
          <th data-field="price">Actions</th>
      </tr>
    </thead>

    <tbody>
      {% for obj in object_list %}
        <tr class='clickable-row' data-href="{% url 'schools:details_schools_country' obj.pk %}">
          <td>{{ obj.pk }}</td>
          <td>{{ obj.country_name }}</td>
          <td>{{ obj.short_name }}</td>
          <td>{{ obj.currency }}</td>
          <td>
            <a href="{% url 'schools:edit_schools_country' obj.pk %}"><i class="large material-icons">mode_edit</i></a>
            <a onClick="DoubleCheckRemove(this);" data-t="{{ obj.pk }}"><i class="large material-icons">delete</i></a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
    </table>
   </div>
 </div>
 <div id="modalRemove" class="modal">
  <div class="modal-content">
    Tem certeza que deseja remover o item selecionado?
    <form id="remove_form" action="" method="post">
      {% csrf_token %}
    </form>
  </div>
  <div class="modal-footer">
    <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">Nao</a>
    <a id="ConfirmDelete" class="modal-action modal-close waves-effect waves-green btn-flat ">Sim</a>
  </div>
</div>

</div>
 <script type="text/javascript">
 jQuery(document).ready(function($) {
    $(".clickable-row").click(function() {
        window.document.location = $(this).data("href");
    });
});
 function DoubleCheckRemove(value){
  $("#remove_form.").attr("action", "schools/country/delete/" + $(this).data("t"));
  $("#modalRemove").openModal();
 }
 $("#ConfirmDelete").click(function(){
    $("#remove_form").submit();
  });
</script>

{% endblock %}

apps/schools/templates/schools_combo/new_school_form.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block header_title %}
<span class="mdl-layout-title">{{ page }}</span>
{% endblock %}
{% block body %}

<div class="container">
    <ul class="collapsible" data-collapsible="accordion">
    <li>
      <div class="collapsible-header active"><i class="material-icons">library_books</i>About the Course</div>
      <div class="collapsible-body">
          <div class="container">
            <form id="course_content" class="col s12" method="post" enctype="multipart/form-data" action="{% url 'schools:new_combo' %}">
              <div class="row">
              {% csrf_token %}
              <div class="input-field col s12">
                {{ form.type_of_combo }}
                <label for="id_type_of_combo" class="active">{{ form.type_of_combo.help_text }}</label>
              </div>
              <div class="input-field col s12">
                {{ form.type_of_course }}
                <label for="id_type_of_source" class="active">{{ form.type_of_course.help_text }}</label>
              </div>
              <div class="input-field col s12">
                {{ form.course_offered }}
                <label for="id_course_offered" class="active">{{ form.course_offered.help_text }}</label>
              </div>
              <div class="input-field col s12">
                {{ form.short_name }}
                <label class="active" for="id_short_name">{{ form.short_name.help_text }}</label>
              </div>
             
              <div class="input-field col s12">
                {{ form.plus }}
                <label class="active" for="id_plus">{{ form.plus.help_text }}</label>
              </div>
            </form>
         </div>
      </div>
    </li>
    <li>
      <div class="collapsible-header"><i class="material-icons">place</i>About Acommodation</div>
      <div class="collapsible-body">
        <div class="container">
          <form id="acommodation_content" class="col s12" method="post">
            <div class="col s12">
              <div class="row">
                <div class="col s4">
                  {{ form.is_beakfest_included }}
                  <label class="active" for="id_is_beakfest_included">{{ form.is_beakfest_included.help_text }}</label>
                </div>
                <div class="col s4">
                  {{ form.is_lunch_included }}
                  <label class="active" for="id_is_lunch_included">{{ form.is_lunch_included.help_text }}</label>
                </div>
                <div class="col s4">  
                  {{ form.is_dinner_included }}
                  <label class="active" for="id_is_dinner_included">{{ form.is_dinner_included.help_text }}</label>
                </div>
              </div>
            </div>
             <div class="col s12">
              <div class="row">
                <div class="col s4">
                  {{ form.wifi_free }}
                  <label class="active" for="id_wifi_free">{{ form.wifi_free.help_text }}</label>
                </div>
                <div class="col s4">
                  {{ form.is_tv_in_the_bedroom }}
                  <label class="active" for="id_is_tv_in_the_bedroom">{{ form.is_tv_in_the_bedroom.help_text }}</label>
                </div>
                <div class="col s4">
                  {{ form.is_wardrobe_in_the_bedroom }}
                  <label class="active" for="id_is_wardrobe_in_the_bedroom">{{ form.is_wardrobe_in_the_bedroom.help_text }}</label>
                </div>
              </div>
            </div>
            <div class="col s12">
              <div class="row">
                <div class="col s4">
                  {{ form.is_air_in_the_badroom }}
                  <label class="active" for="id_is_air_in_the_badroom">{{ form.is_air_in_the_badroom.help_text }}</label>
                </div>
              </div>
            </div>
            <div class="col s12">
              <div class="row">
                <div class="input-field col s12">
                  {{ form.interval_clean_up_the_beadroom }}
                  <label class="active" for="id_interval_clean_up_the_beadroom">{{ form.interval_clean_up_the_beadroom.help_text }}</label>
                </div>
                <div class="input-field col s12">
                  {{ form.duration }}
                  <label class="active" for="id_duration">{{ form.duration.help_text }}</label>
                </div>
                <div class="input-field col s12">
                  {{ form.to_school }}
                  <label class="active" for="id_to_school">{{ form.to_school.help_text }}</label>
                </div>
                <div class="input-field col s12">
                  {{ form.differentials }}
                  <label class="active" for="id_differentials">{{ form.differentials.help_text }}</label>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </li>
    <li>
      <div class="collapsible-header"><i class="material-icons">today</i>Events</div>
      <div class="collapsible-body">
        <div class="container">
          <form id="price_content" class="col s12">
            <div class="input-field col s6">
              {{ form.events_period }}
              <label class="active" for="id_currency">{{ form.events_period.help_text }}</label>
            </div>
          </form>
        </div>
      </div>
    </li>
    <li>
      <div class="collapsible-header"><i class="material-icons">$</i>Price</div>
      <div class="collapsible-body">
        <div class="container">
          <form id="price_content" class="col s12">
            <div class="input-field col s6">
              {{ form.currency }}
              <label class="active" for="id_currency">{{ form.currency.help_text }}</label>
            </div>
            <div class="input-field col s6">
              {{ form.registration_fee }}
              <label class="active" for="id_registration_fee">{{ form.registration_fee.help_text }}</label>
            </div>
            <div class="input-field col s6">
              {{ form.workbook }}
              <label class="active" for="id_workbook">{{ form.workbook.help_text }}</label>
            </div>
            <div class="input-field col s6">
              {{ form.insurance }}
              <label class="active" for="id_insurance">{{ form.insurance.help_text }}</label>
            </div>
            <div class="input-field col s6">
              {{ form.course_change_fee }}
              <label class="active" for="id_course_change_fee">{{ form.course_change_fee.help_text }}</label>
            </div>
            <div class="input-field col s6">
              {{ form.high_season_suplement }}
              <label class="active" for="id_high_season_suplement">{{ form.high_season_suplement.help_text }}</label>
            </div>
          </form>
        </div>
      </div>
    </li>
  </ul>
 	<div class="row">
	    
	    <a id="submit" name="send" class="waves-effect waves-light btn right">Salvar</a>
	  </div>
    
  </div>
</div>
<script type="text/javascript">
	$("#submit").click(function(){
		$("#new_school_form").submit();
	})
    $(document).ready(function() {
    $('select').material_select();
  });

</script>
{% endblock %}